workflows:
  ios_free_build:
    name: iOS Free Build
    max_build_duration: 60

    environment:
      xcode: latest

    scripts:
      - name: Build iOS app
        script: |
          xcodebuild \
            -project "TestThrive.xcodeproj" \
            -scheme "TestThrive" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/TestThrive.xcarchive archive

      - name: Export unsigned IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/TestThrive.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build

    artifacts:
      - build/*.ipa
      - build/**/*.dSYM
